// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPostCategory = `-- name: AttachPostCategory :exec
INSERT INTO post_categories (post_id, category_id)
VALUES ($1, $2)
ON CONFLICT (post_id, category_id) DO NOTHING
`

type AttachPostCategoryParams struct {
	PostID     pgtype.UUID `json:"post_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) AttachPostCategory(ctx context.Context, arg AttachPostCategoryParams) error {
	_, err := q.db.Exec(ctx, attachPostCategory, arg.PostID, arg.CategoryID)
	return err
}

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoriesBySlug = `-- name: CountCategoriesBySlug :one
SELECT count(*) FROM categories
WHERE slug = $1 AND id <> $2
`

type CountCategoriesBySlugParams struct {
	Slug string      `json:"slug"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) CountCategoriesBySlug(ctx context.Context, arg CountCategoriesBySlugParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesBySlug, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPostsInCategory = `-- name: CountPublishedPostsInCategory :one
SELECT count(*) FROM posts p
JOIN post_categories pc ON pc.post_id = p.id
WHERE pc.category_id = $1
  AND p.status = 'PUBLISHED'
  AND p.deleted_at IS NULL
`

func (q *Queries) CountPublishedPostsInCategory(ctx context.Context, categoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPostsInCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, description, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, description, parent_id, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const detachAllPostCategories = `-- name: DetachAllPostCategories :exec
DELETE FROM post_categories WHERE post_id = $1
`

func (q *Queries) DetachAllPostCategories(ctx context.Context, postID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, detachAllPostCategories, postID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, description, parent_id, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description, parent_id, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name, slug, description, parent_id, created_at, updated_at FROM categories
ORDER BY name ASC
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, parent_id, created_at, updated_at FROM categories
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesForPost = `-- name: ListCategoriesForPost :many
SELECT c.id, c.name, c.slug, c.description, c.parent_id, c.created_at, c.updated_at FROM categories c
JOIN post_categories pc ON pc.category_id = c.id
WHERE pc.post_id = $1
ORDER BY c.name ASC
`

func (q *Queries) ListCategoriesForPost(ctx context.Context, postID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, name, slug, description, parent_id, created_at, updated_at FROM categories
WHERE parent_id = $1
ORDER BY name ASC
`

func (q *Queries) ListChildCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsInCategory = `-- name: ListPublishedPostsInCategory :many
SELECT p.id, p.title, p.slug, p.excerpt, p.body, p.status, p.published_at, p.scheduled_at, p.author_id, p.reading_time, p.like_count, p.deleted_at, p.created_at, p.updated_at, p.search_vector FROM posts p
JOIN post_categories pc ON pc.post_id = p.id
WHERE pc.category_id = $1
  AND p.status = 'PUBLISHED'
  AND p.deleted_at IS NULL
ORDER BY p.published_at DESC NULLS LAST, p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublishedPostsInCategoryParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListPublishedPostsInCategory(ctx context.Context, arg ListPublishedPostsInCategoryParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsInCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2,
    slug = $3,
    description = $4,
    parent_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, parent_id, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
