// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByStatus = `-- name: CountCommentsByStatus :many
SELECT status, count(*) AS total
FROM comments
GROUP BY status
`

type CountCommentsByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountCommentsByStatus(ctx context.Context) ([]CountCommentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCommentsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCommentsByStatusRow{}
	for rows.Next() {
		var i CountCommentsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCommentsForModeration = `-- name: CountCommentsForModeration :one
SELECT count(*) FROM comments
WHERE ($1::text IS NULL OR status = $1::text)
`

func (q *Queries) CountCommentsForModeration(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsForModeration, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    post_id, parent_id, author_user_id, author_name, author_email,
    author_ip, body, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, post_id, parent_id, author_user_id, author_name, author_email, author_ip, body, status, created_at, updated_at, edited_at
`

type CreateCommentParams struct {
	PostID       pgtype.UUID `json:"post_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
	AuthorName   string      `json:"author_name"`
	AuthorEmail  string      `json:"author_email"`
	AuthorIp     string      `json:"author_ip"`
	Body         string      `json:"body"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.ParentID,
		arg.AuthorUserID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorIp,
		arg.Body,
		arg.Status,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorIp,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getApprovedCommentByID = `-- name: GetApprovedCommentByID :one
SELECT id, post_id, parent_id, author_user_id, author_name, author_email, author_ip, body, status, created_at, updated_at, edited_at FROM comments
WHERE id = $1 AND post_id = $2 AND status = 'APPROVED'
`

type GetApprovedCommentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) GetApprovedCommentByID(ctx context.Context, arg GetApprovedCommentByIDParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getApprovedCommentByID, arg.ID, arg.PostID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorIp,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, parent_id, author_user_id, author_name, author_email, author_ip, body, status, created_at, updated_at, edited_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorIp,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listApprovedCommentsForPost = `-- name: ListApprovedCommentsForPost :many
SELECT id, post_id, parent_id, author_user_id, author_name, author_email, author_ip, body, status, created_at, updated_at, edited_at FROM comments
WHERE post_id = $1 AND status = 'APPROVED'
ORDER BY created_at ASC
`

func (q *Queries) ListApprovedCommentsForPost(ctx context.Context, postID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listApprovedCommentsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorIp,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsForModeration = `-- name: ListCommentsForModeration :many
SELECT id, post_id, parent_id, author_user_id, author_name, author_email, author_ip, body, status, created_at, updated_at, edited_at FROM comments
WHERE ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCommentsForModerationParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
}

func (q *Queries) ListCommentsForModeration(ctx context.Context, arg ListCommentsForModerationParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsForModeration, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorIp,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentBody = `-- name: UpdateCommentBody :one
UPDATE comments
SET body = $2,
    status = $3,
    edited_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, post_id, parent_id, author_user_id, author_name, author_email, author_ip, body, status, created_at, updated_at, edited_at
`

type UpdateCommentBodyParams struct {
	ID     pgtype.UUID `json:"id"`
	Body   string      `json:"body"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentBody, arg.ID, arg.Body, arg.Status)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorIp,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const updateCommentStatus = `-- name: UpdateCommentStatus :one
UPDATE comments
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, post_id, parent_id, author_user_id, author_name, author_email, author_ip, body, status, created_at, updated_at, edited_at
`

type UpdateCommentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCommentStatus(ctx context.Context, arg UpdateCommentStatusParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentStatus, arg.ID, arg.Status)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorIp,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}
