// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menus.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (name, location)
VALUES ($1, $2)
RETURNING id, name, location, created_at, updated_at
`

type CreateMenuParams struct {
	Name     string `json:"name"`
	Location string `json:"location"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu, arg.Name, arg.Location)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (menu_id, parent_id, position, type, ref_id, url, label)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, menu_id, parent_id, position, type, ref_id, url, label, created_at, updated_at
`

type CreateMenuItemParams struct {
	MenuID   pgtype.UUID `json:"menu_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Position int32       `json:"position"`
	Type     string      `json:"type"`
	RefID    pgtype.UUID `json:"ref_id"`
	Url      string      `json:"url"`
	Label    string      `json:"label"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.MenuID,
		arg.ParentID,
		arg.Position,
		arg.Type,
		arg.RefID,
		arg.Url,
		arg.Label,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.ParentID,
		&i.Position,
		&i.Type,
		&i.RefID,
		&i.Url,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM menus WHERE id = $1
`

func (q *Queries) DeleteMenu(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenu, id)
	return err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, id)
	return err
}

const getMenu = `-- name: GetMenu :one
SELECT id, name, location, created_at, updated_at FROM menus WHERE id = $1
`

func (q *Queries) GetMenu(ctx context.Context, id pgtype.UUID) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenu, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenuByLocation = `-- name: GetMenuByLocation :one
SELECT id, name, location, created_at, updated_at FROM menus
WHERE location = $1 AND location <> ''
`

// Public resolve entry: the single menu assigned to a location (partial-unique
// guarantees at most one). Unassigned menus (location = ”) are never returned.
func (q *Queries) GetMenuByLocation(ctx context.Context, location string) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenuByLocation, location)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMenuItemTranslationLocales = `-- name: ListMenuItemTranslationLocales :many
SELECT locale FROM menu_item_translations
WHERE item_id = $1
ORDER BY locale
`

func (q *Queries) ListMenuItemTranslationLocales(ctx context.Context, itemID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listMenuItemTranslationLocales, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var locale string
		if err := rows.Scan(&locale); err != nil {
			return nil, err
		}
		items = append(items, locale)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemTranslations = `-- name: ListMenuItemTranslations :many
SELECT locale, label FROM menu_item_translations
WHERE item_id = $1
ORDER BY locale
`

type ListMenuItemTranslationsRow struct {
	Locale string `json:"locale"`
	Label  string `json:"label"`
}

func (q *Queries) ListMenuItemTranslations(ctx context.Context, itemID pgtype.UUID) ([]ListMenuItemTranslationsRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemTranslations, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMenuItemTranslationsRow{}
	for rows.Next() {
		var i ListMenuItemTranslationsRow
		if err := rows.Scan(&i.Locale, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, menu_id, parent_id, position, type, ref_id, url, label, created_at, updated_at FROM menu_items
WHERE menu_id = $1
ORDER BY position, created_at
`

// Every item in a menu, ordered by position (then created_at as a stable
// tiebreak). Structural read — labels are the base default-locale values.
func (q *Queries) ListMenuItems(ctx context.Context, menuID pgtype.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItems, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Position,
			&i.Type,
			&i.RefID,
			&i.Url,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsInLocale = `-- name: ListMenuItemsInLocale :many
SELECT
    i.id,
    i.menu_id,
    i.parent_id,
    i.position,
    i.type,
    i.ref_id,
    i.url,
    COALESCE(NULLIF(t.label, ''), i.label) AS label,
    i.created_at,
    i.updated_at
FROM menu_items i
LEFT JOIN menu_item_translations t ON t.item_id = i.id AND t.locale = $2
WHERE i.menu_id = $1
ORDER BY i.position, i.created_at
`

type ListMenuItemsInLocaleParams struct {
	MenuID pgtype.UUID `json:"menu_id"`
	Locale string      `json:"locale"`
}

// Overlay read for the public resolve: every item in a menu with its LABEL
// overlaid by the given locale's translation where present, falling back to the
// base item label for any empty/absent translation. All other columns are
// structural and come straight from the base item row. Ordered by position.
func (q *Queries) ListMenuItemsInLocale(ctx context.Context, arg ListMenuItemsInLocaleParams) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsInLocale, arg.MenuID, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Position,
			&i.Type,
			&i.RefID,
			&i.Url,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenus = `-- name: ListMenus :many
SELECT id, name, location, created_at, updated_at FROM menus
ORDER BY name, created_at
`

func (q *Queries) ListMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.Query(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Menu{}
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMenuItemPosition = `-- name: SetMenuItemPosition :exec
UPDATE menu_items
SET position = $2,
    updated_at = now()
WHERE id = $1
`

type SetMenuItemPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	Position int32       `json:"position"`
}

// Assign a single item's position; used in a loop within one transaction to
// reorder a menu's items (position = index in the ordered id list).
func (q *Queries) SetMenuItemPosition(ctx context.Context, arg SetMenuItemPositionParams) error {
	_, err := q.db.Exec(ctx, setMenuItemPosition, arg.ID, arg.Position)
	return err
}

const updateMenu = `-- name: UpdateMenu :one
UPDATE menus
SET name = $2,
    location = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, location, created_at, updated_at
`

type UpdateMenuParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Location string      `json:"location"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, updateMenu, arg.ID, arg.Name, arg.Location)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET parent_id = $2,
    type = $3,
    ref_id = $4,
    url = $5,
    label = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, menu_id, parent_id, position, type, ref_id, url, label, created_at, updated_at
`

type UpdateMenuItemParams struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Type     string      `json:"type"`
	RefID    pgtype.UUID `json:"ref_id"`
	Url      string      `json:"url"`
	Label    string      `json:"label"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.ParentID,
		arg.Type,
		arg.RefID,
		arg.Url,
		arg.Label,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.ParentID,
		&i.Position,
		&i.Type,
		&i.RefID,
		&i.Url,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMenuItemTranslation = `-- name: UpsertMenuItemTranslation :exec
INSERT INTO menu_item_translations (item_id, locale, label)
VALUES ($1, $2, $3)
ON CONFLICT (item_id, locale) DO UPDATE
SET label = EXCLUDED.label,
    updated_at = now()
`

type UpsertMenuItemTranslationParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	Locale string      `json:"locale"`
	Label  string      `json:"label"`
}

// Insert or update the per-locale label for (item_id, locale). Callers pass a
// NON-default locale (the base item row holds the default-locale label).
func (q *Queries) UpsertMenuItemTranslation(ctx context.Context, arg UpsertMenuItemTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertMenuItemTranslation, arg.ItemID, arg.Locale, arg.Label)
	return err
}
