// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CategoryTranslation struct {
	ID          pgtype.UUID        `json:"id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Locale      string             `json:"locale"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Comment struct {
	ID           pgtype.UUID        `json:"id"`
	PostID       pgtype.UUID        `json:"post_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	AuthorUserID pgtype.UUID        `json:"author_user_id"`
	AuthorName   string             `json:"author_name"`
	AuthorEmail  string             `json:"author_email"`
	AuthorIp     string             `json:"author_ip"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	EditedAt     pgtype.Timestamptz `json:"edited_at"`
}

type EmailVerificationToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type MediaThumbnail struct {
	ID         pgtype.UUID        `json:"id"`
	MediaID    pgtype.UUID        `json:"media_id"`
	Variant    string             `json:"variant"`
	StorageKey string             `json:"storage_key"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Medium struct {
	ID               pgtype.UUID        `json:"id"`
	StorageKey       string             `json:"storage_key"`
	OriginalFilename string             `json:"original_filename"`
	Mime             string             `json:"mime"`
	SizeBytes        int64              `json:"size_bytes"`
	Width            *int32             `json:"width"`
	Height           *int32             `json:"height"`
	Alt              string             `json:"alt"`
	Title            string             `json:"title"`
	Caption          string             `json:"caption"`
	UploadedBy       pgtype.UUID        `json:"uploaded_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OauthAccount struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	EventName   string             `json:"event_name"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	Attempts    int32              `json:"attempts"`
	LastError   *string            `json:"last_error"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
}

type Page struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Body            string             `json:"body"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Template        string             `json:"template"`
	ReadingTime     int32              `json:"reading_time"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SearchVector    interface{}        `json:"search_vector"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
	CanonicalUrl    string             `json:"canonical_url"`
	Noindex         bool               `json:"noindex"`
}

type PageTranslation struct {
	ID              pgtype.UUID        `json:"id"`
	PageID          pgtype.UUID        `json:"page_id"`
	Locale          string             `json:"locale"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
}

type PasswordResetToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID        pgtype.UUID        `json:"id"`
	Action    string             `json:"action"`
	Subject   string             `json:"subject"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Excerpt         string             `json:"excerpt"`
	Body            string             `json:"body"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	ReadingTime     int32              `json:"reading_time"`
	LikeCount       int32              `json:"like_count"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SearchVector    interface{}        `json:"search_vector"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
	CanonicalUrl    string             `json:"canonical_url"`
	Noindex         bool               `json:"noindex"`
}

type PostCategory struct {
	PostID     pgtype.UUID        `json:"post_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PostLike struct {
	PostID    pgtype.UUID        `json:"post_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostTag struct {
	PostID    pgtype.UUID        `json:"post_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostTranslation struct {
	ID              pgtype.UUID        `json:"id"`
	PostID          pgtype.UUID        `json:"post_id"`
	Locale          string             `json:"locale"`
	Title           string             `json:"title"`
	Excerpt         string             `json:"excerpt"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
}

type Revision struct {
	ID         pgtype.UUID        `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Snapshot   []byte             `json:"snapshot"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type SchemaMetum struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Summary         string             `json:"summary"`
	Body            string             `json:"body"`
	Price           string             `json:"price"`
	AreaServed      string             `json:"area_served"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ReadingTime     int32              `json:"reading_time"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SearchVector    interface{}        `json:"search_vector"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
	CanonicalUrl    string             `json:"canonical_url"`
	Noindex         bool               `json:"noindex"`
}

type ServiceFaq struct {
	ID        pgtype.UUID        `json:"id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ServiceFaqTranslation struct {
	ID        pgtype.UUID        `json:"id"`
	FaqID     pgtype.UUID        `json:"faq_id"`
	Locale    string             `json:"locale"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ServiceTranslation struct {
	ID              pgtype.UUID        `json:"id"`
	ServiceID       pgtype.UUID        `json:"service_id"`
	Locale          string             `json:"locale"`
	Title           string             `json:"title"`
	Summary         string             `json:"summary"`
	Body            string             `json:"body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
}

type SiteSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TagTranslation struct {
	ID        pgtype.UUID        `json:"id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	Locale    string             `json:"locale"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	Username          *string            `json:"username"`
	PasswordHash      string             `json:"password_hash"`
	Name              string             `json:"name"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	RoleID            pgtype.UUID        `json:"role_id"`
	Bio               *string            `json:"bio"`
	AvatarPath        *string            `json:"avatar_path"`
	Website           *string            `json:"website"`
	SocialLinks       []byte             `json:"social_links"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	AvatarUrl         *string            `json:"avatar_url"`
}
