// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_translations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePageTranslation = `-- name: DeletePageTranslation :exec
DELETE FROM page_translations
WHERE page_id = $1 AND locale = $2
`

type DeletePageTranslationParams struct {
	PageID pgtype.UUID `json:"page_id"`
	Locale string      `json:"locale"`
}

func (q *Queries) DeletePageTranslation(ctx context.Context, arg DeletePageTranslationParams) error {
	_, err := q.db.Exec(ctx, deletePageTranslation, arg.PageID, arg.Locale)
	return err
}

const getActivePageInLocaleByID = `-- name: GetActivePageInLocaleByID :one
SELECT
    p.id,
    COALESCE(NULLIF(t.title, ''), p.title) AS title,
    p.slug,
    COALESCE(NULLIF(t.body, ''), p.body)   AS body,
    p.status,
    p.published_at,
    p.parent_id,
    p.template,
    p.reading_time,
    COALESCE(NULLIF(t.meta_title, ''), p.meta_title)             AS meta_title,
    COALESCE(NULLIF(t.meta_description, ''), p.meta_description) AS meta_description,
    p.canonical_url,
    p.noindex,
    p.deleted_at,
    p.created_at,
    p.updated_at
FROM pages p
LEFT JOIN page_translations t ON t.page_id = p.id AND t.locale = $2
WHERE p.id = $1 AND p.deleted_at IS NULL
`

type GetActivePageInLocaleByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	Locale string      `json:"locale"`
}

type GetActivePageInLocaleByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Body            string             `json:"body"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Template        string             `json:"template"`
	ReadingTime     int32              `json:"reading_time"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
	CanonicalUrl    string             `json:"canonical_url"`
	Noindex         bool               `json:"noindex"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Load an ACTIVE (non-trashed) page by id with its title/body OVERLAID by the
// given locale's translation where present, falling back to the base row for any
// empty/absent translation field. NULLIF(”) makes an empty translation field
// fall through to COALESCE's base value. Structural columns come straight from
// the base row. The projected row matches the pages column shape so the repo maps
// it with the existing pageFromRow.
func (q *Queries) GetActivePageInLocaleByID(ctx context.Context, arg GetActivePageInLocaleByIDParams) (GetActivePageInLocaleByIDRow, error) {
	row := q.db.QueryRow(ctx, getActivePageInLocaleByID, arg.ID, arg.Locale)
	var i GetActivePageInLocaleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ParentID,
		&i.Template,
		&i.ReadingTime,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CanonicalUrl,
		&i.Noindex,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageTranslation = `-- name: GetPageTranslation :one
SELECT id, page_id, locale, title, body, created_at, updated_at, meta_title, meta_description FROM page_translations
WHERE page_id = $1 AND locale = $2
`

type GetPageTranslationParams struct {
	PageID pgtype.UUID `json:"page_id"`
	Locale string      `json:"locale"`
}

func (q *Queries) GetPageTranslation(ctx context.Context, arg GetPageTranslationParams) (PageTranslation, error) {
	row := q.db.QueryRow(ctx, getPageTranslation, arg.PageID, arg.Locale)
	var i PageTranslation
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Locale,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const getPublishedPageInLocaleBySlug = `-- name: GetPublishedPageInLocaleBySlug :one
SELECT
    p.id,
    COALESCE(NULLIF(t.title, ''), p.title) AS title,
    p.slug,
    COALESCE(NULLIF(t.body, ''), p.body)   AS body,
    p.status,
    p.published_at,
    p.parent_id,
    p.template,
    p.reading_time,
    COALESCE(NULLIF(t.meta_title, ''), p.meta_title)             AS meta_title,
    COALESCE(NULLIF(t.meta_description, ''), p.meta_description) AS meta_description,
    p.canonical_url,
    p.noindex,
    p.deleted_at,
    p.created_at,
    p.updated_at
FROM pages p
LEFT JOIN page_translations t ON t.page_id = p.id AND t.locale = $2
WHERE p.slug = $1 AND p.status = 'PUBLISHED' AND p.deleted_at IS NULL
`

type GetPublishedPageInLocaleBySlugParams struct {
	Slug   string `json:"slug"`
	Locale string `json:"locale"`
}

type GetPublishedPageInLocaleBySlugRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Body            string             `json:"body"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Template        string             `json:"template"`
	ReadingTime     int32              `json:"reading_time"`
	MetaTitle       string             `json:"meta_title"`
	MetaDescription string             `json:"meta_description"`
	CanonicalUrl    string             `json:"canonical_url"`
	Noindex         bool               `json:"noindex"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Public detail read: a published, non-trashed page by slug with its content
// overlaid by the given locale (base fallback per field). Slug/status are shared
// so the slug is the same across locales.
func (q *Queries) GetPublishedPageInLocaleBySlug(ctx context.Context, arg GetPublishedPageInLocaleBySlugParams) (GetPublishedPageInLocaleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPageInLocaleBySlug, arg.Slug, arg.Locale)
	var i GetPublishedPageInLocaleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ParentID,
		&i.Template,
		&i.ReadingTime,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CanonicalUrl,
		&i.Noindex,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPageTranslationLocales = `-- name: ListPageTranslationLocales :many
SELECT locale FROM page_translations
WHERE page_id = $1
ORDER BY locale
`

// The set of locales that already have a translation row for a page — used to
// mark "has translation" indicators on the editor's locale tabs.
func (q *Queries) ListPageTranslationLocales(ctx context.Context, pageID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPageTranslationLocales, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var locale string
		if err := rows.Scan(&locale); err != nil {
			return nil, err
		}
		items = append(items, locale)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageTranslations = `-- name: ListPageTranslations :many
SELECT id, page_id, locale, title, body, created_at, updated_at, meta_title, meta_description FROM page_translations
WHERE page_id = $1
ORDER BY locale
`

// All translation rows for a page (every non-default locale that has one).
func (q *Queries) ListPageTranslations(ctx context.Context, pageID pgtype.UUID) ([]PageTranslation, error) {
	rows, err := q.db.Query(ctx, listPageTranslations, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageTranslation{}
	for rows.Next() {
		var i PageTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Locale,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPageTranslation = `-- name: UpsertPageTranslation :one
INSERT INTO page_translations (page_id, locale, title, body, meta_title, meta_description)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (page_id, locale) DO UPDATE
SET title = EXCLUDED.title,
    body = EXCLUDED.body,
    meta_title = EXCLUDED.meta_title,
    meta_description = EXCLUDED.meta_description,
    updated_at = now()
RETURNING id, page_id, locale, title, body, created_at, updated_at, meta_title, meta_description
`

type UpsertPageTranslationParams struct {
	PageID          pgtype.UUID `json:"page_id"`
	Locale          string      `json:"locale"`
	Title           string      `json:"title"`
	Body            string      `json:"body"`
	MetaTitle       string      `json:"meta_title"`
	MetaDescription string      `json:"meta_description"`
}

// Insert or update the translation row for (page_id, locale). Callers pass a
// NON-default locale (en content lives on the base pages row). Body is sanitized
// by the service before it reaches here.
func (q *Queries) UpsertPageTranslation(ctx context.Context, arg UpsertPageTranslationParams) (PageTranslation, error) {
	row := q.db.QueryRow(ctx, upsertPageTranslation,
		arg.PageID,
		arg.Locale,
		arg.Title,
		arg.Body,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i PageTranslation
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Locale,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}
