// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPosts = `-- name: CountPosts :one
SELECT count(*) FROM posts
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::uuid IS NULL OR author_id = $2::uuid)
`

type CountPostsParams struct {
	Status   *string     `json:"status"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) CountPosts(ctx context.Context, arg CountPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, arg.Status, arg.AuthorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsBySlug = `-- name: CountPostsBySlug :one
SELECT count(*) FROM posts
WHERE slug = $1 AND id <> $2
`

type CountPostsBySlugParams struct {
	Slug string      `json:"slug"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) CountPostsBySlug(ctx context.Context, arg CountPostsBySlugParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsBySlug, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPosts = `-- name: CountPublishedPosts :one
SELECT count(*) FROM posts WHERE status = 'PUBLISHED' AND deleted_at IS NULL
`

func (q *Queries) CountPublishedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedPosts = `-- name: CountTrashedPosts :one
SELECT count(*) FROM posts WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountTrashedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    title, slug, excerpt, body, status, published_at, scheduled_at,
    author_id, reading_time
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at
`

type CreatePostParams struct {
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Excerpt     string             `json:"excerpt"`
	Body        string             `json:"body"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	ReadingTime int32              `json:"reading_time"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Body,
		arg.Status,
		arg.PublishedAt,
		arg.ScheduledAt,
		arg.AuthorID,
		arg.ReadingTime,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePostByID = `-- name: GetActivePostByID :one
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at FROM posts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActivePostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getActivePostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at FROM posts
WHERE slug = $1 AND status = 'PUBLISHED' AND deleted_at IS NULL
`

func (q *Queries) GetPublishedPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasLiked = `-- name: HasLiked :one
SELECT EXISTS (
    SELECT 1 FROM post_likes WHERE post_id = $1 AND user_id = $2
)
`

type HasLikedParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) HasLiked(ctx context.Context, arg HasLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiked, arg.PostID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likePost = `-- name: LikePost :execrows
INSERT INTO post_likes (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
`

type LikePostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDueScheduledPostIDs = `-- name: ListDueScheduledPostIDs :many
SELECT id FROM posts
WHERE status = 'DRAFT'
  AND scheduled_at IS NOT NULL
  AND scheduled_at <= $1
  AND deleted_at IS NULL
ORDER BY scheduled_at
`

func (q *Queries) ListDueScheduledPostIDs(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDueScheduledPostIDs, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at FROM posts
WHERE deleted_at IS NULL
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::uuid IS NULL OR author_id = $4::uuid)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   *string     `json:"status"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.AuthorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at FROM posts
WHERE status = 'PUBLISHED' AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST, created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByAuthor = `-- name: ListPublishedPostsByAuthor :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at FROM posts
WHERE author_id = $1 AND status = 'PUBLISHED' AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListPublishedPostsByAuthor(ctx context.Context, authorID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedPosts = `-- name: ListTrashedPosts :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at FROM posts
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT $1 OFFSET $2
`

type ListTrashedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrashedPosts(ctx context.Context, arg ListTrashedPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listTrashedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeletePost = `-- name: PermanentDeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) PermanentDeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeletePost, id)
	return err
}

const restorePost = `-- name: RestorePost :exec
UPDATE posts SET deleted_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestorePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePost, id)
	return err
}

const setPostLikeCount = `-- name: SetPostLikeCount :exec
UPDATE posts SET like_count = (
    SELECT count(*) FROM post_likes WHERE post_id = $1
)
WHERE id = $1
`

func (q *Queries) SetPostLikeCount(ctx context.Context, postID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setPostLikeCount, postID)
	return err
}

const trashPost = `-- name: TrashPost :exec
UPDATE posts SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TrashPost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, trashPost, id)
	return err
}

const unlikePost = `-- name: UnlikePost :execrows
DELETE FROM post_likes WHERE post_id = $1 AND user_id = $2
`

type UnlikePostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlikePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $2,
    slug = $3,
    excerpt = $4,
    body = $5,
    status = $6,
    published_at = $7,
    scheduled_at = $8,
    reading_time = $9,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Excerpt     string             `json:"excerpt"`
	Body        string             `json:"body"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	ReadingTime int32              `json:"reading_time"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Body,
		arg.Status,
		arg.PublishedAt,
		arg.ScheduledAt,
		arg.ReadingTime,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
