// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPosts = `-- name: CountPosts :one
SELECT count(*) FROM posts
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::uuid IS NULL OR author_id = $2::uuid)
`

type CountPostsParams struct {
	Status   *string     `json:"status"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) CountPosts(ctx context.Context, arg CountPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, arg.Status, arg.AuthorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsBySlug = `-- name: CountPostsBySlug :one
SELECT count(*) FROM posts
WHERE slug = $1 AND id <> $2
`

type CountPostsBySlugParams struct {
	Slug string      `json:"slug"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) CountPostsBySlug(ctx context.Context, arg CountPostsBySlugParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsBySlug, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPosts = `-- name: CountPublishedPosts :one
SELECT count(*) FROM posts WHERE status = 'PUBLISHED' AND deleted_at IS NULL
`

func (q *Queries) CountPublishedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPostsFiltered = `-- name: CountPublishedPostsFiltered :one
SELECT count(*) FROM posts p
WHERE p.status = 'PUBLISHED'
  AND p.deleted_at IS NULL
  AND (
    $1::text IS NULL OR EXISTS (
        SELECT 1 FROM post_categories pc
        JOIN categories c ON c.id = pc.category_id
        WHERE pc.post_id = p.id AND c.slug = $1::text
    )
  )
  AND (
    $2::text IS NULL OR EXISTS (
        SELECT 1 FROM post_tags pt
        JOIN tags t ON t.id = pt.tag_id
        WHERE pt.post_id = p.id AND t.slug = $2::text
    )
  )
`

type CountPublishedPostsFilteredParams struct {
	CategorySlug *string `json:"category_slug"`
	TagSlug      *string `json:"tag_slug"`
}

func (q *Queries) CountPublishedPostsFiltered(ctx context.Context, arg CountPublishedPostsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPostsFiltered, arg.CategorySlug, arg.TagSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedPosts = `-- name: CountTrashedPosts :one
SELECT count(*) FROM posts WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountTrashedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    title, slug, excerpt, body, status, published_at, scheduled_at,
    author_id, reading_time
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector
`

type CreatePostParams struct {
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Excerpt     string             `json:"excerpt"`
	Body        string             `json:"body"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	ReadingTime int32              `json:"reading_time"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Body,
		arg.Status,
		arg.PublishedAt,
		arg.ScheduledAt,
		arg.AuthorID,
		arg.ReadingTime,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getActivePostByID = `-- name: GetActivePostByID :one
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActivePostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getActivePostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts
WHERE slug = $1 AND status = 'PUBLISHED' AND deleted_at IS NULL
`

func (q *Queries) GetPublishedPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getPublishedPostsByIDs = `-- name: GetPublishedPostsByIDs :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts
WHERE id = ANY($1::uuid[])
  AND status = 'PUBLISHED'
  AND deleted_at IS NULL
`

// Hydrate a set of post ids to their published, non-trashed rows. Used by the
// taxonomy archives, which first resolve ordered ids then load the rows. Order
// is re-applied in Go to preserve the archive's ranking.
func (q *Queries) GetPublishedPostsByIDs(ctx context.Context, ids []pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPublishedPostsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasLiked = `-- name: HasLiked :one
SELECT EXISTS (
    SELECT 1 FROM post_likes WHERE post_id = $1 AND user_id = $2
)
`

type HasLikedParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) HasLiked(ctx context.Context, arg HasLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiked, arg.PostID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likePost = `-- name: LikePost :execrows
INSERT INTO post_likes (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
`

type LikePostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDueScheduledPostIDs = `-- name: ListDueScheduledPostIDs :many
SELECT id FROM posts
WHERE status = 'DRAFT'
  AND scheduled_at IS NOT NULL
  AND scheduled_at <= $1
  AND deleted_at IS NULL
ORDER BY scheduled_at
`

func (q *Queries) ListDueScheduledPostIDs(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDueScheduledPostIDs, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts
WHERE deleted_at IS NULL
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::uuid IS NULL OR author_id = $4::uuid)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   *string     `json:"status"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.AuthorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts
WHERE status = 'PUBLISHED' AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST, created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByAuthor = `-- name: ListPublishedPostsByAuthor :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts
WHERE author_id = $1 AND status = 'PUBLISHED' AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListPublishedPostsByAuthor(ctx context.Context, authorID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsFiltered = `-- name: ListPublishedPostsFiltered :many
SELECT p.id, p.title, p.slug, p.excerpt, p.body, p.status, p.published_at, p.scheduled_at, p.author_id, p.reading_time, p.like_count, p.deleted_at, p.created_at, p.updated_at, p.search_vector FROM posts p
WHERE p.status = 'PUBLISHED'
  AND p.deleted_at IS NULL
  AND (
    $3::text IS NULL OR EXISTS (
        SELECT 1 FROM post_categories pc
        JOIN categories c ON c.id = pc.category_id
        WHERE pc.post_id = p.id AND c.slug = $3::text
    )
  )
  AND (
    $4::text IS NULL OR EXISTS (
        SELECT 1 FROM post_tags pt
        JOIN tags t ON t.id = pt.tag_id
        WHERE pt.post_id = p.id AND t.slug = $4::text
    )
  )
ORDER BY p.published_at DESC NULLS LAST, p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsFilteredParams struct {
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
	CategorySlug *string `json:"category_slug"`
	TagSlug      *string `json:"tag_slug"`
}

// Public blog listing with optional, combinable category + tag slug filters. A
// NULL slug param means "no constraint on that axis"; both set means the post
// must match BOTH (intersection). Drafts/trashed are always excluded.
func (q *Queries) ListPublishedPostsFiltered(ctx context.Context, arg ListPublishedPostsFilteredParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsFiltered,
		arg.Limit,
		arg.Offset,
		arg.CategorySlug,
		arg.TagSlug,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedPublishedPosts = `-- name: ListRelatedPublishedPosts :many
SELECT p.id, p.title, p.slug, p.excerpt, p.body, p.status, p.published_at, p.scheduled_at, p.author_id, p.reading_time, p.like_count, p.deleted_at, p.created_at, p.updated_at, p.search_vector, count(*) AS shared_count
FROM posts p
JOIN (
    SELECT pc.post_id AS related_post_id
    FROM post_categories pc
    WHERE pc.category_id IN (
        SELECT pcs.category_id FROM post_categories pcs WHERE pcs.post_id = $1
    )
    UNION ALL
    SELECT pt.post_id AS related_post_id
    FROM post_tags pt
    WHERE pt.tag_id IN (
        SELECT pts.tag_id FROM post_tags pts WHERE pts.post_id = $1
    )
) rel ON rel.related_post_id = p.id
WHERE p.id <> $1
  AND p.status = 'PUBLISHED'
  AND p.deleted_at IS NULL
GROUP BY p.id
ORDER BY shared_count DESC, p.published_at DESC NULLS LAST, p.created_at DESC
LIMIT $2
`

type ListRelatedPublishedPostsParams struct {
	PostID pgtype.UUID `json:"post_id"`
	Limit  int32       `json:"limit"`
}

type ListRelatedPublishedPostsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Excerpt      string             `json:"excerpt"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	ReadingTime  int32              `json:"reading_time"`
	LikeCount    int32              `json:"like_count"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SearchVector interface{}        `json:"search_vector"`
	SharedCount  int64              `json:"shared_count"`
}

// Posts sharing >=1 category OR tag with the given post (laravel parity).
// Self is excluded; only published, non-trashed posts are considered. Results
// are ranked by the number of shared taxonomy terms (most-related first), then
// recency, and limited.
func (q *Queries) ListRelatedPublishedPosts(ctx context.Context, arg ListRelatedPublishedPostsParams) ([]ListRelatedPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listRelatedPublishedPosts, arg.PostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedPublishedPostsRow{}
	for rows.Next() {
		var i ListRelatedPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.SharedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedPosts = `-- name: ListTrashedPosts :many
SELECT id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector FROM posts
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
LIMIT $1 OFFSET $2
`

type ListTrashedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrashedPosts(ctx context.Context, arg ListTrashedPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listTrashedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.ScheduledAt,
			&i.AuthorID,
			&i.ReadingTime,
			&i.LikeCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentDeletePost = `-- name: PermanentDeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) PermanentDeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, permanentDeletePost, id)
	return err
}

const restorePost = `-- name: RestorePost :exec
UPDATE posts SET deleted_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestorePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePost, id)
	return err
}

const setPostLikeCount = `-- name: SetPostLikeCount :exec
UPDATE posts SET like_count = (
    SELECT count(*) FROM post_likes WHERE post_id = $1
)
WHERE id = $1
`

func (q *Queries) SetPostLikeCount(ctx context.Context, postID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setPostLikeCount, postID)
	return err
}

const trashPost = `-- name: TrashPost :exec
UPDATE posts SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TrashPost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, trashPost, id)
	return err
}

const unlikePost = `-- name: UnlikePost :execrows
DELETE FROM post_likes WHERE post_id = $1 AND user_id = $2
`

type UnlikePostParams struct {
	PostID pgtype.UUID `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlikePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $2,
    slug = $3,
    excerpt = $4,
    body = $5,
    status = $6,
    published_at = $7,
    scheduled_at = $8,
    reading_time = $9,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, slug, excerpt, body, status, published_at, scheduled_at, author_id, reading_time, like_count, deleted_at, created_at, updated_at, search_vector
`

type UpdatePostParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Excerpt     string             `json:"excerpt"`
	Body        string             `json:"body"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	ReadingTime int32              `json:"reading_time"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Body,
		arg.Status,
		arg.PublishedAt,
		arg.ScheduledAt,
		arg.ReadingTime,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.ScheduledAt,
		&i.AuthorID,
		&i.ReadingTime,
		&i.LikeCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
