// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumeEmailVerificationToken(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	ConsumePasswordResetToken(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	CountPosts(ctx context.Context, arg CountPostsParams) (int64, error)
	CountPostsBySlug(ctx context.Context, arg CountPostsBySlugParams) (int64, error)
	CountPublishedPosts(ctx context.Context) (int64, error)
	CountTrashedPosts(ctx context.Context) (int64, error)
	CountUsersByEmail(ctx context.Context, email string) (int64, error)
	CountUsersByUsername(ctx context.Context, username *string) (int64, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateRevision(ctx context.Context, arg CreateRevisionParams) (Revision, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeadLetterOutbox(ctx context.Context, arg DeadLetterOutboxParams) error
	EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error
	FetchUnprocessedOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	GetActivePostByID(ctx context.Context, id pgtype.UUID) (Post, error)
	GetEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error)
	GetPublishedPostBySlug(ctx context.Context, slug string) (Post, error)
	GetRevision(ctx context.Context, id pgtype.UUID) (Revision, error)
	GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error)
	GetRoleByKey(ctx context.Context, key string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	GrantPermission(ctx context.Context, arg GrantPermissionParams) error
	HasLiked(ctx context.Context, arg HasLikedParams) (bool, error)
	LikePost(ctx context.Context, arg LikePostParams) (int64, error)
	ListDueScheduledPostIDs(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]pgtype.UUID, error)
	ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]ListPermissionsForRoleRow, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error)
	ListPublishedPostsByAuthor(ctx context.Context, authorID pgtype.UUID) ([]Post, error)
	ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]Revision, error)
	ListRolePermissions(ctx context.Context) ([]ListRolePermissionsRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListTrashedPosts(ctx context.Context, arg ListTrashedPostsParams) ([]Post, error)
	MarkEmailVerified(ctx context.Context, id pgtype.UUID) error
	MarkOutboxProcessed(ctx context.Context, id int64) error
	PermanentDeletePost(ctx context.Context, id pgtype.UUID) error
	RecordOutboxFailure(ctx context.Context, arg RecordOutboxFailureParams) error
	RestorePost(ctx context.Context, id pgtype.UUID) error
	SetPostLikeCount(ctx context.Context, postID pgtype.UUID) error
	SetUserAvatarPath(ctx context.Context, arg SetUserAvatarPathParams) (User, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	TrashPost(ctx context.Context, id pgtype.UUID) error
	UnlikePost(ctx context.Context, arg UnlikePostParams) (int64, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error)
	UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
