// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, key, label, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByKey = `-- name: GetRoleByKey :one
SELECT id, key, label, created_at, updated_at FROM roles WHERE key = $1
`

func (q *Queries) GetRoleByKey(ctx context.Context, key string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByKey, key)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantPermission = `-- name: GrantPermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type GrantPermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) error {
	_, err := q.db.Exec(ctx, grantPermission, arg.RoleID, arg.PermissionID)
	return err
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT p.action, p.subject
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.subject, p.action
`

type ListPermissionsForRoleRow struct {
	Action  string `json:"action"`
	Subject string `json:"subject"`
}

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]ListPermissionsForRoleRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsForRoleRow{}
	for rows.Next() {
		var i ListPermissionsForRoleRow
		if err := rows.Scan(&i.Action, &i.Subject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT r.key AS role_key, p.action, p.subject
FROM role_permissions rp
JOIN roles r ON r.id = rp.role_id
JOIN permissions p ON p.id = rp.permission_id
ORDER BY r.key, p.subject, p.action
`

type ListRolePermissionsRow struct {
	RoleKey string `json:"role_key"`
	Action  string `json:"action"`
	Subject string `json:"subject"`
}

func (q *Queries) ListRolePermissions(ctx context.Context) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionsRow{}
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.RoleKey, &i.Action, &i.Subject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, key, label, created_at, updated_at FROM roles ORDER BY key
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPermission = `-- name: UpsertPermission :one
INSERT INTO permissions (action, subject)
VALUES ($1, $2)
ON CONFLICT (action, subject) DO UPDATE SET action = EXCLUDED.action
RETURNING id, action, subject, created_at
`

type UpsertPermissionParams struct {
	Action  string `json:"action"`
	Subject string `json:"subject"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, upsertPermission, arg.Action, arg.Subject)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRole = `-- name: UpsertRole :one
INSERT INTO roles (key, label)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, updated_at = now()
RETURNING id, key, label, created_at, updated_at
`

type UpsertRoleParams struct {
	Key   string `json:"key"`
	Label string `json:"label"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, upsertRole, arg.Key, arg.Label)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
